### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by fancyweb** [ekino/drupal-debug#2]
- [ ] How to install it ?
- [ ] Quick description
- [ ] List of each actions with a concrete usage case
- [ ] Configuration
- [ ] Composer commands
- [ ] Explain the original DrupalKernel substitution and its goal
- [ ] Usage without composer
- [ ] How to customize the options atm ?

**Comment by mamoot64** [comment]
Hi @fancyweb,

I can take this part if you want ;)

**Comment by fancyweb** [comment]
Thank you but I will take care of the initial version because I think it will be easier for me since it's my code ^^

**Comment by fancyweb** [comment]
https://github.com/ekino/drupal-debug/pull/48
