### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by fancyweb** [ekino/drupal-debug#5]
We need to setup a basic CI, with tests, phpstan and CS fix.

**Comment by mamoot64** [comment]
I can take this part if you want.
CI will be based on Travis-CI.

**Comment by fancyweb** [comment]
This is the option I have used so far : 
`./vendor/bin/php-cs-fixer fix src --rules=@Symfony,@Symfony:risky,array_syntax,ordered_imports,phpdoc_types_order --allow-risky=yes`

`./vendor/bin/phpstan analyse src --level=7 -c quality-analysis/phpstan/phpstan.neon `

**Comment by fancyweb** [comment]
The CI should run on all PHP versions supported by Drupal but only for the last Drupal release I guess.

What we also really need to do is nightly build with the current Drupal dev code so we are aware very early when changes in Drupal core will break this library.

**Comment by fancyweb** [comment]
The CI is now OK. Reopening another issue for the nightly builds.
